### ISSUE TITLE
有人想要世界第一可爱德莉莎版本

### ISSUE THREAD

**Issue by KellyHwong** [BabyAlice/kiana#1]
找德莉莎的图片素材，语音，台本即可。
还有这样的话代码最好抽象一下，方便复用，现在只有kiana一个类。

**Comment by BabyAlice** [comment]
哈哈，才看到呢，，当时做这个的时候 喜欢玩崩坏学园，也没怎么考虑过复用性，有时间了 再优化优化吧。谢谢您的指点， 我会考虑一下的。
